# Generated by Django 3.0 on 2020-02-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200203_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='publish',
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='date'),
        ),
    ]
