# Generated by Django 3.0 on 2020-02-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('code', models.CharField(choices=[('code', 'fa-code'), ('dev', 'fa-dev')], default='code', max_length=10)),
            ],
        ),
    ]
