# Generated by Django 3.0 on 2020-02-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='progress',
            field=models.CharField(choices=[('40', '40%'), ('50', '50%'), ('60', '60%'), ('70', '70%'), ('80', '80%'), ('90', '90%'), ('95', '95%'), ('100', '100%')], default='100', max_length=30),
        ),
        migrations.AlterField(
            model_name='skill',
            name='code',
            field=models.CharField(choices=[('fas fa-code', 'Code'), ('fab fa-python', 'Python'), ('fab fa-react', 'React'), ('fab fa-css3-alt', 'Css3'), ('fab fa-cuttlefish', 'C'), ('fab fa-java', 'Java'), ('fab fa-js-square', 'js'), ('fab fa-linux', 'Linux'), ('fab fa-php', 'Php'), ('fas fa-ruler-combined', 'Ruler'), ('fas fa-database', 'Database'), ('fas fa-terminal', 'Shell'), ('fab fa-node', 'Nodejs'), ('fab fa-aws', 'AWS'), ('fab fa-android', 'Android'), ('fab fa-microsoft', 'Microsoft'), ('fab fa-git', 'Git')], default='Code', max_length=30),
        ),
    ]
